/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as SetsIndexRouteImport } from './routes/sets.index'
import { Route as SetsSetIdRouteImport } from './routes/sets.$setId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsIndexRoute = SetsIndexRouteImport.update({
  id: '/sets/',
  path: '/sets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsSetIdRoute = SetsSetIdRouteImport.update({
  id: '/sets/$setId',
  path: '/sets/$setId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/practice': typeof PracticeRoute
  '/sets/$setId': typeof SetsSetIdRoute
  '/sets/': typeof SetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/practice': typeof PracticeRoute
  '/sets/$setId': typeof SetsSetIdRoute
  '/sets': typeof SetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/practice': typeof PracticeRoute
  '/sets/$setId': typeof SetsSetIdRoute
  '/sets/': typeof SetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add' | '/practice' | '/sets/$setId' | '/sets/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/practice' | '/sets/$setId' | '/sets'
  id: '__root__' | '/' | '/add' | '/practice' | '/sets/$setId' | '/sets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  PracticeRoute: typeof PracticeRoute
  SetsSetIdRoute: typeof SetsSetIdRoute
  SetsIndexRoute: typeof SetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/': {
      id: '/sets/'
      path: '/sets'
      fullPath: '/sets/'
      preLoaderRoute: typeof SetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/$setId': {
      id: '/sets/$setId'
      path: '/sets/$setId'
      fullPath: '/sets/$setId'
      preLoaderRoute: typeof SetsSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  PracticeRoute: PracticeRoute,
  SetsSetIdRoute: SetsSetIdRoute,
  SetsIndexRoute: SetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
